version: '3.5'

services:
    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager:latest
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        environment:
            DB_MYSQL_HOST: mariadb
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: nginxproxymanager
            DB_MYSQL_PASSWORD: nginxproxymanager_password
            DB_MYSQL_NAME: nginxproxymanager_db
        volumes:
            - nginx-proxy-manager-data:/data
            - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
        depends_on:
            - mariadb
        networks:
            - proxy

    mariadb:
        image: yobasystems/alpine-mariadb:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: nginxproxymanager_db
            MYSQL_USER: nginxproxymanager
            MYSQL_PASSWORD: nginxproxymanager_password
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - proxy

networks:
    proxy:

volumes:
    nginx-proxy-manager-data:
    nginx-proxy-manager-letsencrypt:
    mariadb-data:
